//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConcesionarioEntities : DbContext
    {
        public ConcesionarioEntities()
            : base("name=ConcesionarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquiler> alquiler { get; set; }
        public virtual DbSet<carro> carro { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        //public virtual DbSet<tabla_alquiler_Result> tabla_alquiler { get; set; }
    
        public virtual ObjectResult<tabla_alquiler_Result> tabla_alquiler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tabla_alquiler_Result>("tabla_alquiler");
        }

        //public System.Data.Entity.DbSet<GSS.tabla_alquiler_Result> tabla_alquiler_Result { get; set; }
    }
}
